### ISSUE TITLE
`metadatapath` analyzer is being skipped

### ISSUE THREAD

**Issue by eh-am** [grafana/plugin-validator#101]
Hi, the reviewer caught this error when I submitted to grafana, but I expected it to be caught way earlier in my ci lint step:

```
[must fix] The logo in the datasource list is broken. The path in plugin.json point to a non-existing file. Please include a logo in the zip file and/or adjust plugin.json accordingly:
```

Which seems to be analyzed by `metadatapath`:
https://github.com/grafana/plugin-validator/blob/facec498957a62d81cb4f7db446992b64413e0fe/pkg/analysis/passes/metadatapaths/metadatapaths.go#L113

Debugging a little bit, I found that it was simply not being run!

For illustration, use the following `config.yaml` file:

```yaml
global:
  enabled: false
  jsonOutput: false
  reportAll: true

analyzers:
  metadatapaths:
    enabled: true
```

I also found that removing the following loop "fixes" the issue:
https://github.com/grafana/plugin-validator/blob/facec498957a62d81cb4f7db446992b64413e0fe/pkg/runner/runner.go#L82-L86

I didn't look too much so I don't know how that affects other places.
