### ISSUE TITLE
Custom licenses are marked as invalid

### ISSUE THREAD

**Issue by 6nv** [grafana/plugin-validator#55]
I am writing a Grafana panel plugin for work and we are required to use a modified BSD license which is a plain text file labeled `LICENSE` in the root folder of my plugin repository - but when running the plugin validator it fails with the error message `Valid license not found`. Can we generalize the license validator so that it encompasses more licenses?

https://community.grafana.com/t/lint-plugin-step-valid-license-not-found/79683

Thanks!

**Comment by academo** [comment]
This is an expected behaviour from the validator. We only allow specific licenses in plugins (see https://grafana.com/licensing/). 

You can disable this specific rule in your own CI if you like by creating your own config file for the validator with this configuration:

```yaml
global:
  enabled: true
  jsonOutput: false
  reportAll: false

analyzers:
  license:
    enabled: false
```
